name: CI

on:
  push:
    branches-ignore:
      - 'master'

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Java
        uses: actions/setup-java@v1.0.0

        with:
          version: 1.15

      - name: Gradle (Build)
        run: sh gradlew Tags:build build

      - name: Upload artifact (Production JAR)
        uses: actions/upload-artifact@v2

        with:
          name: Production JAR
          path: build/libs/discord-bot-*-SNAPSHOT-all.jar

      - name: Upload artifact (Tags JAR)
        uses: actions/upload-artifact@v2

        with:
          name: Tags JAR
          path: tags/build/libs/Tags-*-SNAPSHOT-all.jar
