name: Publish

on:
  push:
    branches:
      - rewrite

jobs:
  bot:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - run: docker build -t ghcr.io/fabricmc/fabric-discord-bot:latest -t ghcr.io/fabricmc/fabric-discord-bot:${GITHUB_SHA} .
      - run: docker push ghcr.io/fabricmc/fabric-discord-bot:latest
      - run: docker push ghcr.io/fabricmc/fabric-discord-bot:${GITHUB_SHA}

  tags:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - run: docker build -t ghcr.io/fabricmc/fabric-discord-bot-tags:latest -t ghcr.io/fabricmc/fabric-discord-bot-tags:${GITHUB_SHA} tags/
      - run: docker push ghcr.io/fabricmc/fabric-discord-bot-tags:latest
      - run: docker push ghcr.io/fabricmc/fabric-discord-bot-tags:${GITHUB_SHA}
